### ISSUE TITLE
Implement CPU throttling

### ISSUE THREAD

**Issue by dfbag7** [lowleveldesign/process-governor#12]
This is a feature request.

I'd suggest to implement CPU throttling like it is implemented in [BES](http://mion.faireal.net/BES/)
As far as I understand, to throttle CPU usage, BES puts the controlled process on sleep for short periods of time. Implementing a similar functionality in Process Governor would be a big deal.

**Comment by lowleveldesign** [comment]
Thanks for the suggestion. I will look into it.

**Comment by lowleveldesign** [comment]
I finally found a moment to work on it. The new option is -e or --cpurate. If you set both the CPU rate and the CPU affinity, the rate value will be updated accordingly (more in README).

New release is [here](https://github.com/lowleveldesign/process-governor/releases/tag/v2.6.20120.3).
