### ISSUE TITLE
how assign the thread

### ISSUE THREAD

**Issue by ragnaroks** [lowleveldesign/process-governor#13]
i have 16 cores(32 threads),and i executed: 
- `procgov64.exe --cpu=0x1 java.exe -jar benchmark.jar` => use the **0** thread
- `procgov64.exe --cpu=0x2 java.exe -jar benchmark.jar` => use the **1** thread
- `procgov64.exe --cpu=0x3 java.exe -jar benchmark.jar` => use the **0** and **1** threads
- `procgov64.exe --cpu=0x4 java.exe -jar benchmark.jar` => use the **2** thread
- `procgov64.exe --cpu=0x5 java.exe -jar benchmark.jar` => use the **0** and **2** threads
- `procgov64.exe --cpu=0x6 java.exe -jar benchmark.jar` => use the **1** and **2** threads
- `procgov64.exe --cpu=0x7 java.exe -jar benchmark.jar` => use the **0** and **1** and **2** threads
- `procgov64.exe --cpu=0x8 java.exe -jar benchmark.jar` => use the **3** thread
- `procgov64.exe --cpu=0x9 java.exe -jar benchmark.jar` => use the **0** and **3** threads
- `procgov64.exe --cpu=0xA java.exe -jar benchmark.jar` => use the **1** and **3** threads
- `procgov64.exe --cpu=0xB java.exe -jar benchmark.jar` => use the **0** and **1** and **3** threads
- ......

how i can easy to assign the thread?
or how i calculate the last value(like 0xA)?

**Comment by lowleveldesign** [comment]
The CPU mask is 8-bytes long, so supports up to 64 threads. In your case, if you want to enable, for example, the **31** and **0** threads, use the mask `0x80000001`. Does it answer your question?
