### ISSUE TITLE
Help! procgov.exe not recognised 

### ISSUE THREAD

**Issue by warriorn1nja** [lowleveldesign/process-governor#14]
when entering this line of code into an admin cmd.exe -
procgov.exe --maxmem 2G setup
It comes with the 'not recognized' error?

**Comment by lowleveldesign** [comment]
It looks that the system can't find procgov.exe. If it's not in your PATH, try full path to the procgov binary, for example, `c:\temp\procgov.exe --maxmem 2G setup`

**Comment by warriorn1nja** [comment]
Yep done that. I think i may have installed it wrong or something? Is there
a video or tutorial? I've just extracted it to my application folder.

**Comment by lowleveldesign** [comment]
Hmm there is no installation needed - you just copy the .exe file. Could you paste the whole error message you're getting?

**Comment by warriorn1nja** [comment]
'Procgov.exe' is not recognised as an internal or external command,
operable program or batch file.

A generic respose, although I don't belive the ZIP file I've extracted
contains a .exe file inside.

**Comment by lowleveldesign** [comment]
You should use this one: https://github.com/lowleveldesign/process-governor/releases/download/v2.4.20039.2/procgov.zip. Run procgov.exe if your application is 32-bit or procgov64.exe if it's 64-bit.

**Comment by warriorn1nja** [comment]
Yep working now! I must of got the wrong files off the GitHub page. Thank
you!
