### ISSUE TITLE
Does this limit "Working Set" memory?

### ISSUE THREAD

**Issue by douglasg14b** [lowleveldesign/process-governor#15]
I have regular issues where some website will start eating memory in Firefox while my PC is idle.

I'll get up to 32/32GB of memory usage, and 125+GB of pagefile utilization for one reason or another. The thing is, all of the used memory in "Working Set" not "Committed".

Does the memory limits this program sets only work with committed memory, or with Working Set as well?

**Comment by lowleveldesign** [comment]
With the --maxmem option, procgov allows you to set a limit on the committed process memory. However, adding an option for a working set wasn't a big problem, so please download the latest release <https://github.com/lowleveldesign/process-governor/releases/tag/v2.5.20081.1> and try the --maxws option.
