### ISSUE TITLE
How to use the maxws option? It says Parameter is incorrect for it.

### ISSUE THREAD

**Issue by anonimuos** [lowleveldesign/process-governor#16]
How to use the maxws option? It says Parameter is incorrect for it.

**Comment by lowleveldesign** [comment]
Thanks for reporting this. I can reproduce the error:
```
PS me> procgov64.exe --maxws 100M -p 22564
...
ERROR: The parameter is incorrect (0x80004005)
```
Unfortunately, I don't know yet what causes it, and 0x80004005 (E_FAIL) is a very generic error. I tried setting various values for the `MinimumWorkingSet` and `MaximumWorkingSet` values with no success. I need to spend some more time troubleshooting it.

**Comment by lowspecchaos** [comment]
@Annon @lowleveldesign i'm guessing for now we should use "PspMinimumWorkingSet" and "PspMaximumWorkingSet"? These values can be overridden if "performance options" for exe were specified in "Image File Execution Options" under "PerfOptions"

**Comment by lowleveldesign** [comment]
@lowspecchaos, thanks for the suggestion! I wasn't aware of that option and, you're right, it is a good workaround. 

The only downsides are:

- it works only for the newly started processes
- changing IFEO requires admin rights

I hope to find a moment in the coming weeks to debug the error and find a fix for the job object. I will keep this ticket updated.

**Comment by lowleveldesign** [comment]
@anonimuos Please try the latest release (v2.6.20324.1). I updated the binaries on the release page for the v2.6 version.
