### ISSUE TITLE
Working Set Size

### ISSUE THREAD

**Issue by CA10C3SAR** [lowleveldesign/process-governor#18]
Would like to ask if is possible to clear/trims the current working set size of a process by its PID.

Something similar that this program does:
https://www.koshyjohn.com/software/memclean/
It trims all processes working set size, but I would like to just one process instead of everything running. 
Thank you.

**Comment by lowleveldesign** [comment]
It's not really a functionality I would see in the procgov application. Procgov uses a job object to set limits on the processes, but does not "access" the process directly. Correct me if I'm wrong, but trimming sounds like forcing a memory swapping. Unfortunately, I won't be able to help much here. I had a look at the memory cleaner but I'm unsure how it trims the working set.
