### ISSUE TITLE
error CS2001: Source file 'Win32.cs' could not be found

### ISSUE THREAD

**Issue by LongToeBoy** [lowleveldesign/process-governor#21]
when im trying to ./build powershell crashes with this error

**Comment by lowleveldesign** [comment]
Are you sure it's this project? There is no 'build' script or Win32.cs file in process-governor source. You should be able to build process-governor in VS 2017+.

**Comment by LongToeBoy** [comment]
![image](https://user-images.githubusercontent.com/13073946/108761182-87094d80-751c-11eb-9a65-0071ca482278.png)

i dont have VS 2017. but have .NET thought it was possible to just compile with command-line build, with csc. according to build.dat it should output procgov.exe but lacks Win32.cs, ProcessGovernor.cs is there, no problem. anyways if compiling with vs will get rid of error im fine with it, its just an extra step

**Comment by lowleveldesign** [comment]
Ah, sorry for the confusion. That must be some very old build file - I removed it so it won't misguide anyone else. For builds, please use Visual Studio. The binaries are also on the release page.

**Comment by LongToeBoy** [comment]
thanks for clarifying the issue. im installing VS now
