### ISSUE TITLE
GPU limits?

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [lowleveldesign/process-governor#22]
Are GPU limitations possible? (at least memory)

**Comment by lowleveldesign** [comment]
That's a nice idea and I will look into how to implement it. Unfortunately, it needs to wait at least till April as I am busy with other projects at the moment.

**Comment by lowleveldesign** [comment]
Unfortunately, I have bad news 😟 The Job API (that procgov uses) does not have any options for setting GPU limits. If they ever add them, I will be happy to implement them in procgov. But for now, I need to close this ticket unresolved.

**Comment by 0x4E69676874466F78** [comment]
Okay, thanks.
