### ISSUE TITLE
Create a chocolatey installer for this application

### ISSUE THREAD

**Issue by ba-tno** [lowleveldesign/process-governor#23]
This seems like a very useful tool, thank you! I haven't tried it out to its full extent yet.

I try to manage applications on the machines that I administer using the [chocolatey package manager](https://chocolatey.org/) and noticed that process-governor is not on there.

Is it possible to provide a chocolatey package for this application?  
[This page](https://docs.chocolatey.org/en-us/create/create-packages) has more information on the creation of chocolatey packages.

**Comment by lowleveldesign** [comment]
Thanks for the suggestion. I am a bit disappointed about the moderation process for Chocolatey packages. I published a package for another tool I have ([wtrace](https://community.chocolatey.org/packages/wtrace/3.1.21167.4)), and it's been three weeks already in the moderation queue with no feedback. Before I invest any time in a new package creation, I need to be sure that I would be able to publish it. I will keep this issue open.

**Comment by ba-tno** [comment]
I was not aware of the slow administrative processes on Chocolatey's side (I see they flagged it as possible having a virus), that sounds like a bummer indeed. Thanks for keeping it as a suggestion though.

**Comment by lowleveldesign** [comment]
I submitted the package and it's awaiting moderation: <https://community.chocolatey.org/packages/procgov/2.8.21207.1>. I hope it won't take too long to accept it. All updates will be also automatically pushed to chocolatey repository.
