### ISSUE TITLE
does not work with discord

### ISSUE THREAD

**Issue by Epikest** [lowleveldesign/process-governor#26]

**Comment by billy8407** [comment]
Hi, I had tested my discord app in win10 professional x64,
with procgov version of `2.9-1`.
it works fine in maximum memory 250M,
with parameter `-r`.

![image](https://user-images.githubusercontent.com/18491392/149528788-8f36cf4b-c067-4442-80de-f49913ebe2b4.png)

**Comment by lowleveldesign** [comment]
Awesome, I may close this old issue then! @billy8407, thank you so much for testing this 🙌
