### ISSUE TITLE
Add option to limit I/O operations for a process

### ISSUE THREAD

**Issue by dvorapa** [lowleveldesign/process-governor#30]
Usually two main causes of slow PC are memory size and disk speed. If I know I'm gonna run process that uses too much of these two factors, this tool helps me just with one of them, memory. But what about disk speed? Could it be possible to limit also an I/O operations (per second) for a process? To limit disk write rate and disk read rate for a pid?

**Comment by lowleveldesign** [comment]
Procgov uses job API to apply process limits. In the past, it was possible to set the I/O rates using the `SetIoRateControlInformationJobObject` function. Unfortunately, starting with Window 10 v1607, this function is no longer supported. I need to research if there are other options available. It will take time, as I'm busy with other stuff at the moment, but I will update the ticket if I find anything.

**Comment by dvorapa** [comment]
No worries, I bet most of the cases might actually be solved by RAM and CPU limitations. As they limit the internal operations of a process, the I/O operations rate of it might drop in response as well. I will test that strategy for now.
