### ISSUE TITLE
Add support for network latency

### ISSUE THREAD

**Issue by kapsiR** [lowleveldesign/process-governor#36]
## Description
It would be very useful to have the ability to test a process under high network latency conditions without the need of a MiTM / Proxy.

## Details
I did a [quick research](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-job_object_net_rate_control_flags) on the `JOB_OBJECT_NET_*` constants, but I couldn't find anything related to latency...  

So I'm not sure if this would be possible but I would appreciate an additional check / comment 🙏

**Comment by lowleveldesign** [comment]
Hi @kapsiR, thank you for the suggestion. Unfortunately, you are right. I did some research on job network limits, too, and the only one I found was the bandwidth limit. So I added the `--bandwitdth` option to procgov, which uses the `JOBOBJECT_NET_RATE_CONTROL_INFORMATION` structure underneath. I don't have plans to work on the latency feature in the foreseeable future as there is no API I could easily use. I will close this ticket then.

However, if you'd like to play with network packets, you may check the [WinDivert](https://www.reqrypt.org/windivert.html) project. They provide a network filter driver, which you may control from user mode. I remember there were even .NET wrappers for its API available.
