### ISSUE TITLE
procgov64.exe closes right after launching

### ISSUE THREAD

**Issue by A-aalina** [lowleveldesign/process-governor#37]
I don't know what the problem is, but it doesn't work. exe file closes right after launching, that i don't even have time to read the cause of the error.

**Comment by AndreyRGW** [comment]
> I don't know what the problem is, but it doesn't work. exe file closes right after launching, that i don't even have time to read the cause of the error.

Are you running via cmd?

**Comment by lowleveldesign** [comment]
@A-aalina as @AndreyRGW pointed, you need to run procgov from the Command Prompt window, providing the necessary parameters. If it does not work, it should show an error message.

**Comment by lowleveldesign** [comment]
Closing - response timeout expired 😴
