### ISSUE TITLE
Need to be able to pass in CLI options

### ISSUE THREAD

**Issue by linuxgurugamer** [lowleveldesign/process-governor#39]
I am trying to use this with a Unity game which is having some issues with memory.  I need to be able to pass in some options on the command line, but there doesn't seem to have a way to do that.

For example, the CLI I'm trying to run is:

`C:\local\ProcessGoverner\procgov64.exe -m 32G KSP_x64.exe -single-instance -popupwindow -adapter 0`

I tried putting quotes around the CLI parmeters for the program, and they were ignored:
`C:\local\ProcessGoverner\procgov64.exe -m 32G KSP_x64.exe "-single-instance -popupwindow -adapter 0"`

I was able to attach using the pid, but that's awkward to do every time.

**Comment by lowleveldesign** [comment]
Thanks for reporting, it's definitely a bug. Procgov tries to parse the -popupwindow option. I will try to fix it this week.

**Comment by lowleveldesign** [comment]
After checking again, it looks that the following should work:
```
C:\local\ProcessGoverner\procgov64.exe -m 32G -- KSP_x64.exe -single-instance -popupwindow -adapter 0
```
Please try it and let me know if it fixes the problem.

**Comment by linuxgurugamer** [comment]
Yes it does, thank you.

Might I suggest that you add something to the README about it?

Greatly appreciate your quick response

**Comment by linuxgurugamer** [comment]
Amazing!!!
