### ISSUE TITLE
Chrome issue with install method

### ISSUE THREAD

**Issue by michalss** [lowleveldesign/process-governor#4]
Hi ,

first i would like to thank you for success project. Now im having an issue apply memory limit to application chrome with install method. When i do that it giving me black screen window. Can you please have a look? Also would like to ask for a new feature to limit ram per user if that is even possible...

**Comment by michalss** [comment]
What is -r flag, and how to use it. In doc there is not such a thing..

**Comment by lowleveldesign** [comment]
It is present in the latest release, but I also updated the README file in the repository. In short, it will apply the job object to all chrome processes, not only the master one. I'm not sure how you use procgov currently, but an example command line might look as follows: `procgov --maxmem 1G C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. If it does not help, please send me the steps how I can reproduce the "black screen" problem.

**Comment by michalss** [comment]
Using it like this, but i need to make sure that all chrome instances use maxmem and not only master one. Also problem is that if u, for example set 250M for chrome, chrome start crashing on modules or other components. With installation and paramether --install, what is prefferable option in my case, chrome open but as page is completely white.

Command example: procgov64 --install --maxmem 2G "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"

Screen when i run chrome:

**Comment by lowleveldesign** [comment]
I'm afraid I won't be able to fix the `--install` mode. It is the limitation of the Image File Execution Options that procgov uses and the way how chrome works (starting multiple child processes starts multiple Process Governor instances which try to start chrome instances). I will place a warning in the Process Governor README. What I can propose you is to create a simple .bat file and use it as a shortcut to start chrome. The .bat file may contain one line: `procgov64 -r --maxmem 500M "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`. The -r option will apply the limit to each of the starting processes (each process will be allowed to allocate at maximum 500MB of memory).
