### ISSUE TITLE
When I use CMD to start software

### ISSUE THREAD

**Issue by 1qw223** [lowleveldesign/process-governor#41]
When I use CMD to start software, I found i can't to set cpurate
`procgov64.exe -e 50 -p 11140`
`cmd /c Testsoft.exe`
`ERROR: (0x80004005): The parameter is incorrect`

**Comment by lowleveldesign** [comment]
Please try: `procgov64.exe -r -e 50 -p 11140 --
cmd /c Testsoft.exe`. I added the `-r` parameter as you probably want to apply the limit to testsoft.exe and not only cmd.
