### ISSUE TITLE
OneDrive.exe crashing

### ISSUE THREAD

**Issue by akhater** [lowleveldesign/process-governor#42]
Hi thank you for your software

I want to use it specifically to reduce the obscene amount of memory onedrive.exe but everytime I try to run processgov with onedrive.exe the latter crashes 
![image](https://user-images.githubusercontent.com/22518020/193358816-9d1f956b-c27a-4f7b-beab-31f90868e537.png)
is it possible to accomplish what I want?

thank you

**Comment by lowleveldesign** [comment]
Hi, I need more details to learn how you use procgov. What is the command line? Is it installed for onedrive.exe process? It would help a lot if you could record a procmon trace of a onedrive launch and share it with me (sebastian (at) wtrace.net).

**Comment by akhater** [comment]
> Hi, I need more details to learn how you use procgov. What is the command line? Is it installed for onedrive.exe process? It would help a lot if you could record a procmon trace of a onedrive launch and share it with me (sebastian (at) wtrace.net).

Thank you for the reply 

I tried both procgov64 --maxmem 800 --pid ID and procgov64 --maxmem 800 onedrive.exe both lead to the same issue

can u please let me know what else wld u need ?

thanks again

**Comment by lowleveldesign** [comment]
What is the memory limit that you want to set? Currently, you set the limit to 800 bytes which is definitely too small for onedrive. Try setting it to, for example, 100 MB (`--maxmem 100M`) or more.

If the error, persists, I would like to have a look at the [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) trace of the crash. Please start procmon then run procgov64, and after the error happens stop the trace. Save the events to a pml file, zip it and share it with me (if the file is big, upload to gdrive or onedrive and send me the link).

**Comment by akhater** [comment]
> What is the memory limit that you want to set? Currently, you set the limit to 800 bytes which is definitely too small for onedrive. Try setting it to, for example, 100 MB (`--maxmem 100M`) or more.
> 
> If the error, persists, I would like to have a look at the [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) trace of the crash. Please start procmon then run procgov64, and after the error happens stop the trace. Save the events to a pml file, zip it and share it with me (if the file is big, upload to gdrive or onedrive and send me the link).

no sorry I meant 800 MB not 800 bytes sorry :)

let me figure out how to log a trace for you 

thanks again

**Comment by akhater** [comment]
> What is the memory limit that you want to set? Currently, you set the limit to 800 bytes which is definitely too small for onedrive. Try setting it to, for example, 100 MB (`--maxmem 100M`) or more.
> 
> If the error, persists, I would like to have a look at the [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) trace of the crash. Please start procmon then run procgov64, and after the error happens stop the trace. Save the events to a pml file, zip it and share it with me (if the file is big, upload to gdrive or onedrive and send me the link).
[Logfile.zip](https://github.com/lowleveldesign/process-governor/files/9697095/Logfile.zip)
log of the crash

thank u

**Comment by lowleveldesign** [comment]
I noticed that you put a limit on OneDrive process while it's already running. I am not sure if that's the problem, but let's try a different approach. Could you please try installing procgov as a wrapper over OneDrive.exe?

```
procgov64 --install --nogui -m 800M OneDrive.exe
```

Procgov should start automatically with OneDrive process and put the memory limit immediately. Maybe that will prevent OneDrive from crashing. However, if this does not help, I'm not sure what else would. To uninstall procgov, run:

```
procgov64 --uninstall OneDrive.exe
```

**Comment by lowleveldesign** [comment]
@akhater did it work? Could we close the ticket?

**Comment by akhater** [comment]
> ```
> procgov64 --install --nogui -m 800M OneDrive.exe
> ```

Thank you for the follow up, sadly no it didn't solve the issue, it keeps on crashing I had to uninstall

**Comment by lowleveldesign** [comment]
Sorry to hear that. I did a test on my OneDrive account, and it worked. However, I don't have much data on it, so it's probably related to what you store on your account. Thus, I can only recommend reaching out to Microsoft support to fix the problem.
