### ISSUE TITLE
Make an nuget package to do this inside of c#

### ISSUE THREAD

**Issue by JensvandeWiel** [lowleveldesign/process-governor#43]
Hello, I'm currently working on a project where this use of this is very important is there any way to use it inside of a c# program

**Comment by lowleveldesign** [comment]
Unfortunately, I don't have time nor plans to release procgov as a nuget package. But it should be straightforward to convert it to a DLL, if you need it. Check the `Win32JobModule` class, which contains all of the job management code.

**Comment by JensvandeWiel** [comment]
Thanks!
