### ISSUE TITLE
procgov doesnt work when running .bat script

### ISSUE THREAD

**Issue by JensvandeWiel** [lowleveldesign/process-governor#44]
its limited on 100MB but goes over

![image](https://user-images.githubusercontent.com/85284773/193461538-8766bb54-7a2f-42c9-ad88-a12c5670cd97.png)

command used: ./procgov64.exe -m 100M start.bat

bat script contents: steamcmd\steamapps\common\U3DS\Unturned.exe -port:25444 -players:20 -nographics -batchmode -pei -gold -nosync -pve -sv

**Comment by JensvandeWiel** [comment]
when i add -r it doesn't work at all

**Comment by JensvandeWiel** [comment]
so the command: steamcmd\steamapps\common\U3DS\Unturned.exe -port 25444 -players 20 -nographics -batchmode -pei -gold -nosync -pve -sv


works in the bat script but then it crashes and memory dump says:
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
so probably something with permissions

**Comment by lowleveldesign** [comment]
It is probably related to the permissions of the memory page. It could be that the application does not correctly handle memory limits. In that case, there is nothing we can do. Have you tried setting the limit higher? Why do you use the .bat file? You could as well try `procgov64 -m 100M -- steamcmd\steamapps\common\U3DS\Unturned.exe -port 25444 -players 20 -nographics -batchmode -pei -gold -nosync -pve -sv`. But as I wrote, it could be that the limit is too low for this application.

**Comment by JensvandeWiel** [comment]
Ill try that when im home!

**Comment by JensvandeWiel** [comment]
fixed!
