### ISSUE TITLE
Add option to add multiple none-child processes to a job process

### ISSUE THREAD

**Issue by chk-mytoys** [lowleveldesign/process-governor#50]
It would be handy if it would be possible to add multiple processes, that are not child processes, to one job object.

For example by allowing: -pid 1234,4321,5555

Use case: I have multiple large processes and want to limit them as a group to not overload the machine,

**Comment by lowleveldesign** [comment]
It took me a while to implement this 😅, but it's finally released. Please download release 2.12 and give it a try.
