### ISSUE TITLE
--maxmem and --recursive - Limit for all child processes?

### ISSUE THREAD

**Issue by crimcol** [lowleveldesign/process-governor#51]
Hello, not sure if I'm doing that correct.
This is my command:
`procgov64 --maxmem=2048M --recursive --verbose "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe"`

The goal is to make a memory limit 2048M for the entire Visual Studio process including all child processes. 
But it still exceeds the limit:
![image](https://user-images.githubusercontent.com/4273048/205156841-627e1751-2927-40a5-b6df-0c8195a401a9.png)

Does it work different? or wrong parameters?

**Comment by lowleveldesign** [comment]
Hi, the option you're looking for is `--maxjobmem=2G` instead of `--maxmem=2G`. However, I'm not sure how VS will handle this. It may not function properly as its memory consumption is usually much higher :disappointed:
