### ISSUE TITLE
Executable parameters are parsed as command line parameters

### ISSUE THREAD

**Issue by kylelyk** [lowleveldesign/process-governor#52]
Unless I’m misunderstanding the documentation, it should be possible to call Process Governor like so:
```
procgov64.exe notepad.exe -t
```

However this brings up the help documentation for Process Governor. Replacing the `-t` with something else like `-a` works. It seems that Process Governor is reading parameters that are specified after the executable name. It even breaks with parameters which start with `-t` like `procgov64.exe notepad.exe -thumbnail`.

**Comment by lowleveldesign** [comment]
You need to use `--` to separate procgov parameters from the target app, for example: `procgov64.exe -- notepad.exe -thumbnail`. I do mention that in the GitHub README, but I should probably also add a note in the procgov help.
