### ISSUE TITLE
Bitdefender flags as malware

### ISSUE THREAD

**Issue by anthonyg2003** [lowleveldesign/process-governor#53]
Bitdefender is flagging procgov64.exe as malware with threat name "Atc4.Detection".

What could be the reason for this?

**Comment by lowleveldesign** [comment]
No idea, but it's a false positive for sure. I'm not using BitDefender, but I just checked the latest version of procgov64.exe on virus total and there are no issues reported: <https://www.virustotal.com/gui/file/9a29c129ed7e21da77c07167ea52c6480afefe50fe8dd6d24ca79e3eff7e043f>.
