### ISSUE TITLE
"System cannot find the file specified" for Teams.exe

### ISSUE THREAD

**Issue by anthonyg2003** [lowleveldesign/process-governor#54]
A single instance of Teams seems to run around 10 teams.exe processes, and so to keep it under control, I tried using the maxjobmem option:

procgov64 -r --maxjobmem 200M -- teams.exe

which returned:
![image](https://user-images.githubusercontent.com/19936471/227639600-2f386ade-0714-4529-8f60-9fede01940be.png)

Does the process executable file need to be in the PATH? I tried using the file path in the command line and that returned a parsing error.

Using a single PID instead of teams.exe works in that it executes eventually - although takes sometimes minutes and the process just seems to end, but trying multiple PIDs fails with a "ERROR: Not enough quota available to process this command." But even if that worked, not sure that would result in what I want since I ultimately want to restrict all the teams.exe processes and teams just seems to spawn new ones. 

![image](https://user-images.githubusercontent.com/19936471/227646147-294af35a-6f74-4ffd-8c33-c12e29b7441c.png)

**Comment by lowleveldesign** [comment]
If teams.exe is not in the PATH then you need to provide the full path to the executable, for example:

```
procgov64 -r -m 700M C:\Users\{username}\AppData\Local\Microsoft\Teams\current\Teams.exe
```

Regarding the quota issue and problems with Teams, procgov won't fix the application. Unfortunately, Teams require a lot of memory and when you set the limit too low you will either break the application or make it too slow. I'm not sure what's your scenario, but maybe you should rather look at options to limit the physical memory (--minws, --maxws) or total job memory (--maxjobmem)
