### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MawMawLon** [lowleveldesign/process-governor#55]
Hi, i recently found this and got curious with its feature. 
but I have no clue on how to properly use it

I noticed that my microsoft edge started slowing down ever since I run the software
and don't know how to revert its action
I already reinstalled the microsoft edge but it's still slow

How do i remove/uninstall/revert the process-gov?

**Comment by lowleveldesign** [comment]
To uninstall use -u with the same path as you used when you were installing procgov, for example, `-u msedge.exe`.

**Comment by MawMawLon** [comment]
> To uninstall use `--uninstall` with the same path as you used when you were installing procgov, for example, `--uninstall msedge.exe`.

Hi thank you for replying.

I actually just downloaded the latest zip at "releases"

then I run the procgov64.exe and it just instantly closed. 
there was no installation that happened
but my msedge became drastically slow after restarting my pc.

So i really don't know how to uninstall it since i dont know which path it installed to on my pc. and dont know how to use that command sorry for being clueless about this.

**Comment by lowleveldesign** [comment]
Ah, I see. Then there is no need to worry. Procgov does not install anywhere, you run it directly from the place where you downloaded it (or extracted it). To remove it, just remove the exe and zip file. If you only double-clicked procgov64.exe, it showed help and closed. It did not modify your system. If you want to use it, please open command prompt (cmd.exe) and then use the parameters described in [README](https://github.com/lowleveldesign/process-governor/blob/master/README.md)

**Comment by MawMawLon** [comment]
> Ah, I see. Then there is no need to worry. Procgov does not install anywhere, you run it directly from the place where you downloaded it (or extracted it). To remove it, just remove the exe and zip file. If you only double-clicked procgov64.exe, it showed help and closed. It did not modify your system. If you want to use it, please open command prompt (cmd.exe) and then use the parameters described in [README](https://github.com/lowleveldesign/process-governor/blob/master/README.md)

But i think it did modify my msedge? since procgov is the only application i run before it became slow. like its cpu usage is limited.

**Comment by lowleveldesign** [comment]
How do you know CPU usage is limited? Procgov does not pick processes at random (edge in this case) and limits them.
