### ISSUE TITLE
Add option to set process priority

### ISSUE THREAD

**Issue by stephanwehr** [lowleveldesign/process-governor#59]
Example:
`procgov64.exe -r -e 5 -m 256M --priority=BelowNormal -- notepad.exe`

Option values:
```
Idle        Use IDLE priority class
BelowNormal Use BELOWNORMAL priority class
Normal      Use NORMAL priority class
AboveNormal Use ABOVENORMAL priority class
High        Use HIGH priority class
Realtime    Use REALTIME priority class
```

With `-r`, also apply the priority to all child processes.

Resources:
- [Scheduling Priorities](https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities)

**Comment by lowleveldesign** [comment]
Sorry it took that long, but I wanted to merge this change with others in version 3.0. And I finally released it :)

**Comment by stephanwehr** [comment]
No need for apologies, when it's done it's done ;) I will give it a try, thanks
