### ISSUE TITLE
Feature request: Kill all processes (and their children) inside job on job close.

### ISSUE THREAD

**Issue by MarekKnapek** [lowleveldesign/process-governor#62]
Feature request: Kill all processes (and their children) inside job on job close. Of course if process-governor is closed all jobs it created gets closed too. I believe this is one of possible job limits job creator is able to impose on job object. This feature would be useful for example in case I run some kind of script or batch operation, get tired of waiting for it to finish, and decide to kil/stop it. Or in case the batch operation finishes, but some child processes keep lingering around. For example Visual Studio keeps some PDB server process alive after closing. Just by pressing CTRL+C to kill parent process-governor would result in closing the job object and thus killing all the children spawned as part of my batch operation. Today, I need to hunt all children in some sort of Task Manger-like application that is able to display parent-child process relationship such as Process Explorer or Process Hacker / System Informer and kill them one by one. This would also ensure no lingering process is keeping files opened after the batch is done and blocking directory move/cleanup.

**Comment by lowleveldesign** [comment]
A new --terminate-job-on-exit flag will be available soon, in v2.13
