### ISSUE TITLE
ERROR: 拒绝访问。 (0x80004005)

### ISSUE THREAD

**Issue by xianchengyue** [lowleveldesign/process-governor#63]
Hello
I ran a command as administrator "procgov64 --cpurate=60 --pid=58480", but get feedback "Max CPU rate:                               60%

ERROR: Access denied。 (0x80004005)" What's going on here?
Thank you for your time.

**Comment by lowleveldesign** [comment]
Hi, what was the process you tried to limit?

**Comment by fgggid** [comment]
Such as dwm.exe (desktop window manager).

**Comment by lowleveldesign** [comment]
Please try the latest release (3.0). The issue should be fixed now.
