### ISSUE TITLE
Sometimes procgov can't create a process.

### ISSUE THREAD

**Issue by AndreyRGW** [lowleveldesign/process-governor#64]
procgov cannot create a process, but after several attempts it creates it.

log from cmd:
```
C:\Users\RGWyo>procgov64 --cpurate=60 --minws=1M --maxws=8192M --recursive G:\1\ELDEN RING v.1.10 (2022)\Elden Ring\Game\modengine2_launcher.exe
Process Governor v2.12.2363.8 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Max CPU rate:                               60%
Minimum WS memory (MB):                     01
Maximum WS memory (MB):                     8 192

All configured limits will also apply to the child processes.

Press Ctrl-C to end execution without terminating the process.

[2024-01-26 15:32:41.518] [stderr] [error] Couldn't create process: 10dd

C:\Users\RGWyo>procgov64 --cpurate=60 --minws=1M --maxws=8192M --recursive G:\1\ELDEN RING v.1.10 (2022)\Elden Ring\Game\modengine2_launcher.exe
Process Governor v2.12.2363.8 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Max CPU rate:                               60%
Minimum WS memory (MB):                     01
Maximum WS memory (MB):                     8 192

All configured limits will also apply to the child processes.

Press Ctrl-C to end execution without terminating the process.

[2024-01-26 15:32:42.404] [stderr] [error] Couldn't create process: 10dd

C:\Users\RGWyo>procgov64 --cpurate=60 --minws=1M --maxws=8192M --recursive G:\1\ELDEN RING v.1.10 (2022)\Elden Ring\Game\modengine2_launcher.exe
Process Governor v2.12.2363.8 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Max CPU rate:                               60%
Minimum WS memory (MB):                     01
Maximum WS memory (MB):                     8 192

All configured limits will also apply to the child processes.

Press Ctrl-C to end execution without terminating the process.

[2024-01-26 15:32:43.211] [stderr] [error] Couldn't create process: 10dd

C:\Users\RGWyo>procgov64 --cpurate=60 --minws=1M --maxws=8192M --recursive G:\1\ELDEN RING v.1.10 (2022)\Elden Ring\Game\modengine2_launcher.exe
Process Governor v2.12.2363.8 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Max CPU rate:                               60%
Minimum WS memory (MB):                     01
Maximum WS memory (MB):                     8 192

All configured limits will also apply to the child processes.

Press Ctrl-C to end execution without terminating the process.

*on this attempt everything started *

```

**Comment by AndreyRGW** [comment]
Checked 2.11, procgov works perfectly on it and there are no such errors

**Comment by AndreyRGW** [comment]
I also noticed that "--install" stopped working on 2.12: cmd appears for a fraction of a second and closes, but the program doesn't start

**Comment by lowleveldesign** [comment]
There were no major changes in procgov between those version so I have no clue why the old one might be working. Please try the debug build of procgov (attached to this comment) and provide me with the more detailed error message. I've seen issues with the minws/maxws limits in the past, so it could be that it's the Windows itself that's unstable here.

[procgov64.zip](https://github.com/lowleveldesign/process-governor/files/14072907/procgov64.zip)

**Comment by AndreyRGW** [comment]
> There were no major changes in procgov between those versions so I have no clue why the old one might be working. Please try the debug build of procgov (attached to this comment) and provide me with the more detailed error message. I've seen issues with the minws/maxws limits in the past, so it could be that it's the Windows itself that's unstable here.
> 
> [procgov64.zip](https://github.com/lowleveldesign/process-governor/files/14072907/procgov64.zip)

From my observations:
1) If I run a program through the cmd, the error "[stderr] [error] Couldn't create process: 10dd" is still there and fully reproducible.
2) But "--install" now works without fail and all programs start as they should.

**Comment by lowleveldesign** [comment]
This error message: 

```
[2024-01-26 15:32:43.211] [stderr] [error] Couldn't create process: 10dd
```

does not come from procgov, but from modengine2_launcher.exe and it is a very generic error (ERROR_INVALID_OPERATION). Without debugging this process it's hard to tell why they are reporting it. I'm afraid there is not much I can do here.

Regarding the --install option, this bug is actually fixed, but I haven't had time to make a release yet. I will do it quite soon once I fix a few more bugs. In the meantime you may build it by yourself or use the version that I attached to the previous comment. It should run properly.

**Comment by AndreyRGW** [comment]
> This error message:
> 
> ```
> [2024-01-26 15:32:43.211] [stderr] [error] Couldn't create process: 10dd
> ```
> 
> does not come from procgov, but from modengine2_launcher.exe and it is a very generic error (ERROR_INVALID_OPERATION). Without debugging this process it's hard to tell why they are reporting it. I'm afraid there is not much I can do here.
> 
> Regarding the --install option, this bug is actually fixed, but I haven't had time to make a release yet. I will do it quite soon once I fix a few more bugs. In the meantime you may build it by yourself or use the version that I attached to the previous comment. It should run properly.

I noticed bug (on your debug version) when I tried to restrict an already running stable diffusion process (python.exe):
```
C:\Users\RGWyo>procgov64 --minws=1M --maxws=20480M --recursive --pid=14432
Process Governor v1.0.0.0 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Minimum WS memory (MB):                     01
Maximum WS memory (MB):                     20 480

All configured limits will also apply to the child processes.

ERROR: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully.
   at ProcessGovernor.NtApi.CheckWin32Result[T](T)
   at ProcessGovernor.NtApi.SetProcessEnvironmentVariables(Int32, Dictionary`2)
   at ProcessGovernor.ProcessModule.<AssignProcessToJobObject>g__OpenOrCreateJob|2_0(<>c__DisplayClass2_0&, <>c__DisplayClass2_1&)
   at ProcessGovernor.ProcessModule.AssignProcessToJobObject(Int32, SessionSettings)
   at ProcessGovernor.Program.Main(String[])
```

**Comment by lowleveldesign** [comment]
Sorry, that was a stupid mistake on my side. I updated the dependencies and did not fully test. Try this one please.
[Uploading procgov64.zip…]()

**Comment by AndreyRGW** [comment]
> Sorry, that was a stupid mistake on my side. I updated the dependencies and did not fully test. Try this one please.
> 
> [procgov64.zip](https://github.com/lowleveldesign/process-governor/files/14073102/procgov64.zip)

This version works fine, no problems with --install, and binds to already running processes without errors. Thanks!
