### ISSUE TITLE
pass on exit code %errorlevel% of governed process

### ISSUE THREAD

**Issue by klin333** [lowleveldesign/process-governor#66]
Hi,

When a task is run under process governor, the error status code of the governed process seems to get lost, and is not passed on by procgov. See example below, showing a success status code 0 even though i tried to cat a non-existent file. 

Is it possible to always return the %errorlevel% status code of the governed process, when procgov itself encountered no errors.

Thanks 

```
C:\Users\xxx\workspace\bin\procgov>ls
procgov32.exe  procgov32.pdb  procgov64.exe  procgov64.pdb

C:\Users\xxx\workspace\bin\procgov>cat doesnotexist.txt
cat: doesnotexist.txt: No such file or directory

C:\Users\xxx\workspace\bin\procgov>echo %errorlevel%
1

C:\Users\xxx\workspace\bin\procgov>procgov64.exe --maxmem 10G -- cat.exe doesnotexist.txt
Process Governor v1.0.0.0 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Maximum committed memory (MB):              10,240

Press Ctrl-C to end execution without terminating the process.

cat: doesnotexist.txt: No such file or directory

C:\Users\xxx\workspace\bin\procgov>echo %errorlevel%
0

C:\Users\xxx\workspace\bin\procgov>
```

**Comment by lowleveldesign** [comment]
Thanks for the suggestion. I think that when no --nowait option is provided, I will return an error code when procgov or the target application fails. I plan to do some work on this project in the coming weeks, so this should be ready for the next release.

**Comment by lowleveldesign** [comment]
Starting from v2.13 procgov will return the exit code of the initial process (the one provided in the command line, as in your example).
