### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [lowleveldesign/process-governor#68]
Does this work with Win 7?

Thanks

**Comment by lowleveldesign** [comment]
Most options should, but I'm no longer testing on Win 7, so it's hard to tell.

**Comment by harryray33** [comment]
Thanks, do you have any plans for a GUI for this?

**Comment by lowleveldesign** [comment]
I already started working on a GUI, but it will definitely take some time to finish it. I also haven't decided yet on which license I will release it.
