### ISSUE TITLE
It's impossible to attach to a process owned by a different user

### ISSUE THREAD

**Issue by lowleveldesign** [lowleveldesign/process-governor#7]
When you try to attach procgov (even as admin) to a process run by a different user, you will get ERROR: Access is denied (0x80004005). SeDebugPrivilege fixes the problem.

**Comment by lowleveldesign** [comment]
Fixed in the latest release.

**Comment by lacostenycoder** [comment]
I just installed this on Windows 10. Getting this error logged in PowerShell with admin privileges. 
```
PS C:\Windows\system32> procgov64.exe -m 2G -p 17556
Process Governor v2.12.2363.8 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Maximum committed memory (MB):              2,048

ERROR: Access is denied. (0x80004005)
PS C:\Windows\system32>
```

**Comment by lacostenycoder** [comment]
Update: So the process I was trying to limit was vmmem which is virtual machine memory utilized by wsl.exe.  When I used `procgov64.exe -m 2G wsl.exe` It worked without errors.
