### ISSUE TITLE
ERROR: Access is denied. (0x80040005) when using with nxlog.exe

### ISSUE THREAD

**Issue by kicsiburcsi** [lowleveldesign/process-governor#70]
Receives the following error when trying to use the software with NXLog Agent
![2a1d90db-a076-4591-accd-581a4bcdc355](https://github.com/lowleveldesign/process-governor/assets/175109305/2db3cbc5-cee5-4e4a-b59a-72505b8c7c81)

This is the ps script I am using:

$workingdir = "C:\Program Files\procgov"
restart-service nxlog
$nxlog = (get-process nxlog | select -expand id)
& "$workingdir\procgov64.exe" --maxmem 200M --cpu 1 --cpurate 20 --pid $nxlog

**Comment by lowleveldesign** [comment]
Please add -v option to the procgov64.exe arguments and show the output. What is the account of the nxlog service?

**Comment by kicsiburcsi** [comment]
Just to be clear, I appended `-v` to the end of the last line in the ps script. The output is below:
![image](https://github.com/lowleveldesign/process-governor/assets/175109305/fcb13717-5ebb-48d2-8245-e7efda38cbba)

The nxlog service runs with the local system account.
![image](https://github.com/lowleveldesign/process-governor/assets/175109305/609a87ed-7070-4722-aa9d-9bc824512448)

**Comment by lowleveldesign** [comment]
I will need to do some debugging to see if I may fix this problem in procgov.

In the meantime, try running procgov as SYSTEM as well, using, for example, [psexec](https://learn.microsoft.com/en-us/sysinternals/downloads/psexec):

```
"$workingdir\psexec" -s -i "$workingdir\procgov64.exe" --maxmem 200M --cpu 1 --cpurate 20 --pid $nxlog
```

You may skip the -i (interactive) option if you don't need to see the procgov output.

**Comment by lowleveldesign** [comment]
I might have found the reason of this Access Denied. There are still some processes for which you may need the psexec workaround, but most should work fine. Please try the latest release (3.0).
