### ISSUE TITLE
Does not take effect when the number of dual CPU logical threads exceeds 64

### ISSUE THREAD

**Issue by qq1053831109** [lowleveldesign/process-governor#72]
We need to set CPU grouping

**Comment by lowleveldesign** [comment]
Yes, procgov does not support more than 64 CPUs at the moment. One reason for that was that I did not have access to a machine where I could test such configuration. So my question is: do you have access to an environment with more than 64 CPUs and will it be possible to test the new release(s) of procgov there?

**Comment by qq1053831109** [comment]
Even if it exceeds 32, association cannot be set

**Comment by qq1053831109** [comment]
i use procgov32.exe. cmd is  procgov32.exe -c=0xffff00000000 -p 29043 。  it work like -c=0xffffffff。

**Comment by lowleveldesign** [comment]
that might explain why >32 does not work. Can you try procgov64?

**Comment by qq1053831109** [comment]
procgov64 is work ok. but i need use procgov32.exe for 32 bit  process。

**Comment by qq1053831109** [comment]
procgov64.exe -c=0xf0000000000 -p 10580
Process Governor v2.13.24103.12 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

CPU affinity mask:                          0xF0000000000

ERROR: The target process has different bitness than procgov. Please use procgov32 for 32-bit processes and procgov64 for 64-bit processes

**Comment by lowleveldesign** [comment]
I'm going to remove this restriction in the next release of procgov and distribute only the 64-bit version. I will update this ticket once it's ready. In the meantime, you could try compiling procgov with [this restriction](https://github.com/lowleveldesign/process-governor/blob/480d942b6ae67b1ba6444c877bb7e702f007859f/procgov/ProcessModule.cs#L30) removed. The limits should work fine - the bitness requirement was needed for other features to work.

**Comment by qq1053831109** [comment]
Thank you, you can also try to solve the problem with 2 CPUs. Exceeding 64 logical threads. Used when CPUs are grouped. I will provide you with feedback

**Comment by qq1053831109** [comment]
Alternatively, you can rent a machine from Amazon. I have an e5-2673v4 * 2 computer

**Comment by lowleveldesign** [comment]
Thanks, I will definitely look into that.

**Comment by lowleveldesign** [comment]
@qq1053831109 , please do not add comments to unrelated issues. The 3.0 release is almost ready, but it has a lot of changes and I need a bit more time for additional testing and documentation. However, if you're eager to try and test it, you may build the code from the master branch or use the executable attached to this ticket. Check the [README](https://github.com/lowleveldesign/process-governor?tab=readme-ov-file#limit-cpu-usage-of-a-process-cpu-affinity) how to set group and NUMA affinities.

[procgov.zip](https://github.com/user-attachments/files/18034530/procgov.zip)

**Comment by lowleveldesign** [comment]
Release published
