### ISSUE TITLE
version 3.0.24342 WIN32 ERROR: 0x80004005 A device attached to the system is not functioning.

### ISSUE THREAD

**Issue by octaviobh** [lowleveldesign/process-governor#76]
C:\Users\Octavio Home\Downloads\PROGRAMS\Windows Tools\Process Governor>procgov
WIN32 ERROR: 0x80004005
System.ComponentModel.Win32Exception (31): A device attached to the system is not functioning.
   at ProcessGovernor.SystemInfoModule.<GetSystemInfo>g__GetNumaNodes|0_0() + 0x283
   at ProcessGovernor.SystemInfoModule.GetSystemInfo() + 0xd
   at ProcessGovernor.Program.<Main>d__3.MoveNext() + 0x1e8

**Comment by lowleveldesign** [comment]
Could you please let me know what the windows version is?

**Comment by octaviobh** [comment]
Device name OctavioNBProcessor Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHzInstalled RAM 8.00 GB (7.88 GB usable)Device ID 21A53D4F-65AD-4DFF-911D-3A9293F8C982Product ID 00325-80714-37684-AAOEMSystem type 64-bit operating system, x64-based processorPen and touch No pen or touch input is available for this display
Edition Windows 10 HomeVersion 22H2Installed on ‎11/‎02/‎2023OS build 19045.2965Experience Windows Feature Experience Pack 1000.19041.1000.0


    On Saturday, December 7, 2024 at 02:00:30 PM GMT-5, Sebastian Solnica ***@***.***> wrote:  
 
 


Could you please let me know what the windows version is?

**Comment by lowleveldesign** [comment]
Thanks. Now, I'm quite sure it's the Windows Home edition limit (a really unexpected one). I will look into it in the coming days.

**Comment by lowleveldesign** [comment]
I don't have a possibility to test the fix on Windows Home. Could you please check if the version attached to this ticker runs OK or throws an error? Please paste the full error message as before if it still there.

[procgov.zip](https://github.com/user-attachments/files/18134488/procgov.zip)

**Comment by octaviobh** [comment]
Runs OK !!.
C:\Users\Octavio Home\Downloads\PROGRAMS\Windows Tools\Process Governor\ProcGov as Test>procgovProcess Governor v1.0.0.0 - sets limits on processesCopyright (C) 2024 Sebastian Solnica
Use --help to print the available options.
=== SYSTEM INFORMATION ===
NUMA Node 0:  Processor Group 0: 000000000000000F (CPUs: 0,1)
Total Physical Memory (MB):          8,064Available Physical Memory (MB):      1,470Total Committed Memory (MB):         10,405Current Committed Memory Limit (MB): 16,256


    On Saturday, December 14, 2024 at 01:07:39 AM GMT-5, Sebastian Solnica ***@***.***> wrote:  
 
 


I don't have a possibility to test the fix on Windows Home. Could you please check if the version attached to this ticker runs OK or throws an error? Please paste the full error message as before if it still there.

procgov.zip

**Comment by lowleveldesign** [comment]
Perfect 👍. Thank you for checking. I will make an update to the official release either tomorrow or on Monday.

**Comment by lowleveldesign** [comment]
Release updated. Thanks again for reporting and testing.

**Comment by octaviobh** [comment]
Again, prerelease runs ok !. Thanks.

C:\Users\Octavio Home\Downloads\PROGRAMS\Windows Tools\Process Governor\ProcGov as Test PreRelease>procgovProcess Governor v3.0.24350.15 - sets limits on processesCopyright (C) 2024 Sebastian Solnica
Use --help to print the available options.
=== SYSTEM INFORMATION ===
NUMA Node 0:  Processor Group 0: 000000000000000F (CPUs: 0,1)
Total Physical Memory (MB):          8,064Available Physical Memory (MB):      1,625Total Committed Memory (MB):         10,772Current Committed Memory Limit (MB): 16,256


    On Sunday, December 15, 2024 at 02:49:53 AM GMT-5, Sebastian Solnica ***@***.***> wrote:  
 
 


Release updated. Thanks again for reporting and testing.
