### ISSUE TITLE
Move config and log in "C:\ProgramData\ProcessGovernor\"

### ISSUE THREAD

**Issue by mipsou** [lowleveldesign/process-governor#77]
pelasse respect good practice

thank you

**Comment by mipsou** [comment]
### Feature Request: Specify Log Directory for Process Governor

#### 1. Request to Allow Logs in `ProgramData`
Currently, Process Governor logs are written in the same directory as the executable, which may not comply with modern application management practices. For better file organization and adherence to conventions, it would be helpful to enable logs to be redirected to a folder like `C:\ProgramData`.

---

#### 2. Proposed Solution
Add support for a `--logdir` option in the Process Governor command-line arguments to allow users to specify the directory where logs should be stored.

Example command:
```cmd
"C:\Program Files\ProcesssGovernor\Process Governor.exe" --config "C:\ProgramData\ProcessGovernor\config.json" --logdir "C:\ProgramData\ProcessGovernor\logs"

**Comment by mipsou** [comment]
### Feature Request: Specify Log Directory for Process Governor

#### 1. Request to Allow Logs in `ProgramData`
Currently, Process Governor logs are written in the same directory as the executable, which may not comply with modern application management practices. For better file organization and adherence to conventions, it would be helpful to enable logs to be redirected to a folder like `C:\ProgramData`.

---

#### 2. Proposed Solution
Add support for a `--logdir` option in the Process Governor command-line arguments to allow users to specify the directory where logs should be stored.

Example command:
```cmd
"C:\Program Files\ProcesssGovernor\Process Governor.exe" --config "C:\ProgramData\ProcessGovernor\config.json" --logdir "C:\ProgramData\ProcessGovernor\logs"

**Comment by mipsou** [comment]
3. Steps to Implement (Current Workaround)
While this feature is not natively supported, users can manually handle log redirection through a combination of command-line options and scripting.

Create a Folder for Logs

Navigate to C:\ProgramData and create a subfolder:
C:\ProgramData\ProcessGovernor\logs
Modify Command to Redirect Logs

Update the Process Governor shortcut or batch file to include a log directory:
cmd
Copier le code
"C:\Program Files\ProcesssGovernor\Process Governor.exe" --config "C:\ProgramData\ProcessGovernor\config.json" --logdir "C:\ProgramData\ProcessGovernor\logs"

**Comment by mipsou** [comment]
Automate Folder Creation

Use a batch file to ensure the log folder exists before Process Governor starts:
cmd
Code
@echo off
if not exist "C:\ProgramData\ProcessGovernor\logs" mkdir "C:\ProgramData\ProcessGovernor\logs"
"C:\Program Files\ProcesssGovernor\Process Governor.exe" --config "C:\ProgramData\ProcessGovernor\config.json" --logdir "C:\ProgramData\ProcessGovernor\logs"
Optional: Add Log Rotation

Prevent logs from growing indefinitely by automatically deleting logs older than 7 days:
cmd
Copier le code
forfiles /p "C:\ProgramData\ProcessGovernor\logs" /s /m *.log /d -7 /c "cmd /c del @file"
3. Expected Benefits
Logs are cleanly separated from executables, improving portability and maintainability.
Adheres to application development conventions by using ProgramData for configuration and log files.
Reduces clutter in the application directory.
5. Feature Implementation
Adding native support for --logdir would improve the user experience by removing the need for manual scripting. This feature could be optional, with logs continuing to default to the current directory if --logdir is not specified.

**Comment by lowleveldesign** [comment]
Hi, are you sure it's the right repository? This process governor does not use any config and does not produce any log files.

**Comment by mipsou** [comment]
Sorry for my mistake.
you can close

**Comment by mipsou** [comment]
thank for your fast anwer

**Comment by mipsou** [comment]
I made a mistake. I chose the wrong project.

my bad

**Comment by lowleveldesign** [comment]
No worries ☺️
