### ISSUE TITLE
Return code when get memory limit and time limit

### ISSUE THREAD

**Issue by MAAF72** [lowleveldesign/process-governor#9]
How to detect if the program is terminated by memory limit/time limit base on return code?
Thanks

**Comment by lowleveldesign** [comment]
The exit code for timeout is always 1, but in all other cases, I return the exit code of the process, which ran under the job object. So the exit code is not a reliable way to check the reason for termination. You may, however, use the -v flag and check the procgov console output. The timeout will result in a message: "Clock time limit passed - terminating", while the memory limit will print ""Process <pid> exceeded its memory limit".
